default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password:

development:
  <<: *default
  database: film_development

test:
  <<: *default
  database: film_test

production:
  <<: *default
  database: storage/production.sqlite3
